whyred: gps: Add namespace prefix for move() Fix: device/xiaomi/sm6150-common/gps/utils/LocIpc.cpp:315:24: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]             mIpcRecver(move(ipcRecver)) {}                        ^                        std::
Change-Id: I2ecbbd580c26a3993751b0acb646b1371d963930
Signed-off-by: Nanhumly <admin@warbler.cc>
Signed-off-by: Ghosuto <clash.raja10@gmail.com>
Signed-off-by: Arijit78 <sahaarijit2007@gmail.com>